### ISSUE TITLE
[Backend][Feature] Setup user authentication in django

### ISSUE THREAD

**Issue by dhanushthakkalapally** [Automate-India/eat-bear#1]
**Description:**
As a user of the application, I would like to sign up into the application and login into the application using the email and password used to sign up into the application.

**Tasks:**

- [x] Setup sign-up in the django application
- [ ] Setup user signup form in the frontend of the application
- [x] Setup login endpoint in the applicaion
- [ ] Setup login view in the frontend of the application

**Acceptance Criteria:**
User should sign up and login in to the application
